name: Python App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi pandas uvicorn

    - name: Run dummy script for 24f2008883@ds.study.iitm.ac.in
      run: |
        echo "This is a placeholder step to include email in the name field"
